[green_agent]
agentbeats_id = "019bc4f3-9e0f-7ba3-8fee-9291241a4d98"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", LOG_LEVEL = "INFO" }
#image = "green-agent:latest"
#env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" }

[[participants]]
name = "pro_debater"
image = "purple-agent:latest"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" }

[[participants]]
name = "con_debater"
image = "purple-agent:latest"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" }

[config]
topic = "Should artificial intelligence be regulated?"
num_rounds = 2
